DROP TABLE IF EXISTS EMPLOYEES;
CREATE TABLE IF NOT EXISTS EMPLOYEES(
EMP_ID INTEGER PRIMARY KEY,
NAME TEXT,
DEPARTMENT TEXT,
SALARY INTEGER);
INSERT INTO EMPLOYEES(EMP_ID,NAME,DEPARTMENT,SALARY) VALUES
(01,'ALICE','HR',50000),
(02,'BOB','IT',65000),
(03,'CLARA','FINANCE',70000),
(04,'DAVID','IT',60000),
(05,'EMMA','HR',55000),
(06,'FAISAL','MARKETING',48000),
(07,'GRACE','FINANCE',72000),
(08,'HENRY','IT',67000);
SELECT * FROM EMPLOYEES;
SELECT SUM(SALARY) AS TOTAL_SALARY FROM EMPLOYEES;
SELECT AVG(SALARY) AS AVERAGE_SALARY FROM EMPLOYEES;
SELECT COUNT(DISTINCT DEPARTMENT) AS TOTAL_DEPARTMENTS FROM EMPLOYEES;
SELECT MIN(SALARY) AS MINIMUM_SALARY FROM EMPLOYEES;
SELECT MAX(SALARY) AS MAXIMUM_SALARY FROM EMPLOYEES;