DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE IF NOT EXISTS EMPLOYEE(
E_ID TEXT PRIMARY KEY,
E_NAME TEXT,
STATUS TEXT,
ADDRESS TEXT);
INSERT OR IGNORE INTO EMPLOYEE(E_ID,E_NAME,STATUS,ADDRESS) VALUES
('101','SIMI','SECURITY GUARD','DHAKA'),
('102','ROHIT','SECURITY GUARD','CHITTAGONG'),
('103','TINA','RECEPTIONIST','NOAKHALI'),
('104','RIHAB','RECEPTIONIST','RANGPUR'),
('105','PINTU','CHEF','TANGAIL'),
('106','SHARIF','GENERAL MANAGER','CHANDPUR'),
('107','SALAM','ROOSTER PLANNER','SYLHET'),
('108','GOVINDO','TECHNICIAN','NOAKHALI'),
('109','SHIKDAR','FRONT OFFICE MANAGER','MYMENSINGH'),
('110','ZAFREEN','FOOD & BEVERAGE MANAGER','CHITTAGONG'),
('111','FARHANA','INTERN','DHAKA'),
('112','SAFIKA','CHIEF CHEF','BOGURA');
SELECT * FROM EMPLOYEE;
SELECT * FROM EMPLOYEE WHERE ADDRESS='NOAKHALI';
SELECT * FROM EMPLOYEE WHERE (ADDRESS='RANGPUR' OR ADDRESS='DHAKA') AND (STATUS='SECURITY GUARD' OR STATUS='INTERN' OR STATUS='TECHNICIAN');