DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE IF NOT EXISTS CUSTOMER(
CUSTOMER_ID INTEGER PRIMARY KEY,
NAME TEXT,
CITY TEXT,
GRADE INTEGER);
INSERT INTO CUSTOMER(CUSTOMER_ID,NAME,CITY,GRADE) VALUES
(01,'ALICE JOHNSON','NEW YORK',120),
(02,'BRIAN SMITH','CHICAGO',95),
(03,'CLARA MARTINEZ','NEW YORK',85),
(04,'DAVID LEE','LOS ANGELES',110),
(05,'EMMA THOMPSON','NEW YORK',105),
(06,'FAISAL RAHMAN','HOUSTON',130),
(07,'GRACE KIM','NEW YORK',101),
(08,'HENRY ZHAO','BOSTON',99),
(09,'ISABELLA ROSSI','MIAMI',102),
(10,'JACK WILSON','NEW YORK',70);
SELECT * FROM CUSTOMER;
SELECT * FROM CUSTOMER WHERE CITY='NEW YORK' OR GRADE>100;
SELECT * FROM CUSTOMER WHERE CITY='NEW YORK' AND GRADE>100;