--ACTIVITY 1
--not null is used to ensure that every student record has a name
DROP TABLE IF EXISTS STUDENT;
CREATE TABLE IF NOT EXISTS STUDENT(
ROLL_NO TEXT PRIMARY KEY,
NAME TEXT NOT NULL,
ADDRESS TEXT,
PHONE TEXT,
AGE INTEGER);
--INSERT SAMPLE DATA LINE INTO THE STUDENT TABLE
INSERT OR IGNORE INTO STUDENT (ROLL_NO, NAME, ADDRESS, PHONE, AGE) VALUES
('1','RAM','DELHI','*****',18),
('2','RAMESH','GURGAON','*****',18),
('3','SUJIT','ROHTAK','*****',20),
('4','SURESH','DELHI','*****',18),
('5','AMAN','ROHTAK','*****',20),
('6','HARSH','GURGAON','*****',18);
--USE OF UPDATE
UPDATE STUDENT
SET ROLL_NO=20 WHERE NAME='SUJIT'; 
--SELECT ALL RECORDS FROM THE STUDENT TABLE TO VERIFY INSERTION
SELECT * FROM STUDENT;
--QUERY STUDENTS WHO ARE 18 YEARS OLD AND LIVE IN DELHI
SELECT * FROM STUDENT WHERE AGE=18 AND ADDRESS='DELHI';
--QUERY STUDENTS WHO ARE 18 YEARS OLD AND NAMED RAM
SELECT * FROM STUDENT WHERE AGE=18 AND NAME='RAM';
--QUERY STUDENTS NAMED RAM OR SUJIT
SELECT * FROM STUDENT WHERE NAME='RAM' OR NAME='SUJIT';
--QUERY STUDENT NAMED RAM OR AGED 20
SELECT * FROM STUDENT WHERE NAME='RAM' OR AGE=20;
--QUERY STUDENT AGED 18 AND NAMED RAM OR RAMESH
SELECT * FROM STUDENT WHERE AGE=18 AND (NAME='RAM' OR NAME= 'RAMESH');
--USE OF LIKE
SELECT * FROM STUDENT WHERE ADDRESS LIKE 'G%';
--ACTIVITY 2
DROP TABLE IF EXISTS PRODUCT;
CREATE TABLE IF NOT EXISTS PRODUCT(
PRO_ID TEXT PRIMARY KEY,
PRO_NAME TEXT,
PRO_PRICE INTEGER,
PRO_COM TEXT);
INSERT OR IGNORE INTO PRODUCT(PRO_ID,PRO_NAME,PRO_PRICE,PRO_COM) VALUES
('101','MOTHER BOARD','3200','15'),
('102','KEYBOARD','450','12'),
('103','ZIP DRIVE','250','16'),
('104','SPEAKER','550','14'),
('105','MONITOR','5000','16'),
('106','DVD DRIVE','900','11'),
('107','CD DRIVE','800','12'),
('108','PRINTER','2600','12'),
('109','REFILL CARTRIDGE','350','13'),
('110','MOUSE','250','13');
SELECT PRO_NAME,PRO_PRICE
FROM PRODUCT WHERE PRO_PRICE=(SELECT MIN(PRO_PRICE) FROM PRODUCT);
SELECT PRO_NAME,PRO_PRICE
FROM PRODUCT WHERE PRO_PRICE=(SELECT MAX(PRO_PRICE) FROM PRODUCT);