--ACTIVITY 1
CREATE TABLE IF NOT EXISTS NOBEL_WIN(
YEAR INTEGER,
SUBJECT TEXT,
WINNER TEXT,
COUNTRY TEXT,
CATEGORY TEXT);
INSERT INTO NOBEL_WIN(YEAR,SUBJECT,WINNER,COUNTRY,CATEGORY) VALUES
(1970,'PHYSICS','HANNES ALFVEN','SWEDEN','SCIENTIST'),
(1970,'PHYSICS','LOUIS NEEL','FRANCE','SCIENTIST'),
(1971,'PHYSICS','PAUL','FRANCE','SCIENTIST'),
(1971,'CHEMISTRY','HAMILTON','SWEDEN','LINGUIST'),
(1972,'LITERATURE','BERNARD KELSON','GERMANY','ECONOMIST'),
(1972,'ECONOMICS','JOSEPH','RUSSIA','ECONOMIST'),
(1973,'BIOLOGY','PHILIPS','USA','PRIME MINISTER'),
(1980,'BIOLOGY','MARTIN','USA','PRESIDENT'),
(1981,'PHYSIOLOGY','HANNAH','HUNGARY','SCIENTIST'),
(1975,'PHYSICS','PETER','CHILE','SCIENTIST');
SELECT * FROM NOBEL_WIN WHERE SUBJECT NOT LIKE 'P%';
--ACTIVITY 2
CREATE TABLE IF NOT EXISTS DEPARTMENT(
EMPLOYEE_ID TEXT,
NAME TEXT,
DEPARTMENT_ID TEXT,
MANAGER_ID TEXT,
SALARY REAL);
INSERT INTO DEPARTMENT (EMPLOYEE_ID,NAME,DEPARTMENT_ID,MANAGER_ID,SALARY) VALUES
('100','STEVEN KING','90','100',24000),
('101','NEENA KOCCHAR','90','100',17000),
('102','LEX DEHAAN','90','102',9000),
('103','BRUCE LEE','60','103',4800),
('104','DIANA WILLS','60','103',25000),
('105','VALLI PATOR','50','100',4200),
('1973','LUV HAMI','60','102',5000),
('106','DAVID AUSTIN','90','100',6000);
--QUERY TO FIND OUT THE NO OF EMPLOYEES UNDER EACH DEPARTMENT
SELECT DEPARTMENT_ID AS "DEPARTMENT CODE",
COUNT(*) AS "NO OF EMPLOYEES" FROM DEPARTMENT GROUP BY DEPARTMENT_ID;
--QURY TO COUNT SUM OF SALARY IN EACH DEPARTMENT
SELECT DEPARTMENT_ID, SUM(SALARY) AS "TOTAL SALARY" FROM DEPARTMENT GROUP BY DEPARTMENT_ID;
--QUERY TO COUNT NO OF EMPLOYEES AND SUM THE SALARY IN EACH DEPARTMENT
SELECT DEPARTMENT_ID AS "DEPARTMENT CODE", COUNT(*) AS "NO OF EMPLOYEES",
SUM(SALARY) AS "TOTAL SALARY" FROM DEPARTMENT GROUP BY DEPARTMENT_ID;
--QUERY TO SUM THE SALARY OF EMPLOYEES WITH A SPECIFIC MANAGER
SELECT DEPARTMENT_ID AS "DEPARTMENT CODE", SUM(SALARY) AS "TOTAL SALARY"
FROM DEPARTMENT WHERE MANAGER_ID='103' GROUP BY DEPARTMENT_ID;
--QUERY TO FIND DEPARTMENTS WITH MORE THAN 2 EMPLOYEES
SELECT DEPARTMENT_ID, COUNT(*) AS "NO OF EMPLOYEES" FROM DEPARTMENT 
GROUP BY DEPARTMENT_ID HAVING COUNT(*) >2;